### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by josefredohd** [mo-thunderz/XamarinBleCodeBehind#1]
I need to make an application in Xamarin using bluetooth, when a specific string is received from the ESP32 board, show a message in Xamarin, could this work with what is shown in the video?

**Comment by mo-thunderz** [comment]
Yes, that is relatively straight forward. Just use "Notify" and you should
be fine

Regards,
Sander

Op wo 24 mei 2023 om 05:16 schreef josefredohd ***@***.***>:
